sudo: false
language: python

cache: pip

python:
  - "3.8"
  - "3.7"
  - "3.6"

env:
  - DJANGO="Django>=2.0,<2.1"
  - DJANGO="Django>=2.1,<2.2"
  - DJANGO="Django>=2.2,<3.0"
  - DJANGO="Django>=3.0,<3.1"
  - DJANGO="https://github.com/django/django/archive/master.tar.gz"

matrix:
  exclude:
    - python: "3.8"
      env: DJANGO="Django>=2.0,<2.1"
    - python: "3.8"
      env: DJANGO="Django>=2.1,<2.2"
  allow_failures:
    - env: DJANGO="https://github.com/django/django/archive/master.tar.gz"

install:
  - travis_retry pip install $DJANGO
  - travis_retry pip install psycopg2==2.8.4
  - travis_retry pip install celery==4.1.1

services:
  - postgresql

script:
  - python -Wall runtests.py
