sudo: false
language: python

cache: pip

python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"

env:
  - DJANGO="django==1.9.2"
  - DJANGO="django==1.8.9"
  - DJANGO="django==1.7.10"
  - DJANGO="django==1.6.11"
  - DJANGO="django==1.5.12"
  - DJANGO="django==1.4.22"

matrix:
  exclude:
    - python: "3.5"
      env: DJANGO="django==1.7.10"
    - python: "3.5"
      env: DJANGO="django==1.6.11"
    - python: "3.5"
      env: DJANGO="django==1.5.12"
    - python: "3.5"
      env: DJANGO="django==1.4.22"

    - python: "3.4"
      env: DJANGO="django==1.4.22"

    - python: "3.3"
      env: DJANGO="django==1.9.2"
    - python: "3.3"
      env: DJANGO="django==1.4.22"

install:
  - travis_retry pip install $DJANGO
  - travis_retry pip install psycopg2==2.6.1
  - travis_retry pip install django-celery==3.1.17
  - travis_retry pip install futures     # For python 2.7

services:
  - postgresql

before_script:
  - createdb test

script:
  - python runtests.py
